# Generated by Django 4.1.13 on 2024-03-11 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0016_order_orderitem_delete_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='image',
            field=models.ImageField(null=True, upload_to='Product_images.img'),
        ),
    ]
