# Generated by Django 4.1.13 on 2024-03-11 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0017_categories_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='endper',
            field=models.IntegerField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='categories',
            name='startper',
            field=models.IntegerField(max_length=10, null=True),
        ),
    ]
